package app.music.utils.musicstate

object MusicStateConstantUtils {

    const val PREF_LAST_MUSIC_LIST = "PREF_LAST_MUSIC_LIST"
    const val PREF_LAST_COUNT_TIME = "PREF_LAST_COUNT_TIME"
    const val PREF_LAST_PLAYED_MUSIC_OBJECT = "PREF_LAST_PLAYED_MUSIC_OBJECT"
    const val PREF_LAST_PLAYED_MUSIC_OBJECT_TYPE = "PREF_LAST_PLAYED_MUSIC_OBJECT_TYPE"
    const val PREF_LAST_PLAYED_MUSIC_OBJECT_TYPE_MUSIC = "PREF_LAST_PLAYED_MUSIC_OBJECT_TYPE_MUSIC"
    const val PREF_LAST_PLAYED_MUSIC_OBJECT_TYPE_ONLINE_MUSIC = "PREF_LAST_PLAYED_MUSIC_OBJECT_TYPE_ONLINE_MUSIC"
    const val PREF_REPLAY_STATE = "PREF_REPLAY_STATE"
    const val PREF_SHUFFLE_STATE = "PREF_SHUFFLE_STATE"
}
