package app.music.utils.theme

object ThemeConstantUtils {

    const val PREF_CURRENT_THEME_MODE = "PREF_CURRENT_THEME_MODE"
    const val PREF_DARK_MODE = "PREF_DARK_MODE"
    const val PREF_LIGHT_MODE = "PREF_LIGHT_MODE"

    const val PREF_BASE_THEME_NAME = "PREF_BASE_THEME_NAME"
    const val PREF_BASE_THEME_BLACK = "PREF_BASE_THEME_BLACK"
    const val PREF_BASE_THEME_INDIGO = "PREF_BASE_THEME_INDIGO"
    const val PREF_BASE_THEME_MAGENTA = "PREF_BASE_THEME_MAGENTA"
    const val PREF_BASE_THEME_DEEP_SKY_BLUE = "PREF_BASE_THEME_DEEP_SKY_BLUE"
    const val PREF_BASE_THEME_NAVY = "PREF_BASE_THEME_NAVY"
    const val PREF_BASE_THEME_MAROON = "PREF_BASE_THEME_MAROON"
    const val PREF_BASE_THEME_DARK_RED = "PREF_BASE_THEME_DARK_RED"
    const val PREF_BASE_THEME_BROWN = "PREF_BASE_THEME_BROWN"
}
