package app.music.utils.intent

object IntentConstantUtils {

    const val EXTRA_ALBUM_OBJECT_TO_DETAIL_ALBUM = "EXTRA_ALBUM_OBJECT_TO_DETAIL_ALBUM"
    const val EXTRA_MUSIC_OBJECT_TO_DETAIL_PLAY_MV = "EXTRA_MUSIC_OBJECT_TO_DETAIL_PLAY_MV"
    const val EXTRA_ARTIST_OBJECT_TO_DETAIL_ARTIST = "EXTRA_ARTIST_OBJECT_TO_DETAIL_ARTIST"
    const val EXTRA_GENRE_OBJECT_TO_DETAIL_GENRE = "EXTRA_GENRE_OBJECT_TO_DETAIL_GENRE"
    const val EXTRA_PLAYLIST_OBJECT_TO_DETAIL_PLAYLIST = "EXTRA_PLAYLIST_OBJECT_TO_DETAIL_PLAYLIST"
    const val EXTRA_FOLDER_OBJECT_TO_DETAIL_FOLDER = "EXTRA_FOLDER_OBJECT_TO_DETAIL_FOLDER"
}
