package app.music.utils.sort

object SortConstantUtils {

    const val PREF_ALBUM_ORDER_BY = "PREF_ALBUM_ORDER_BY"
    const val PREF_ALBUM_SORT = "PREF_ALBUM_SORT"
    const val PREF_ALBUM_SORT_BY_ALPHABET = "PREF_ALBUM_SORT_BY_ALPHABET"
    const val PREF_ALBUM_SORT_BY_NUMBER_OF_SONGS = "PREF_ALBUM_SORT_BY_NUMBER_OF_SONGS"

    const val PREF_SONG_ORDER_BY = "PREF_SONG_ORDER_BY"
    const val PREF_SONG_SORT = "PREF_SONG_SORT"
    const val PREF_SONG_SORT_BY_ALBUM = "PREF_SONG_SORT_BY_ALBUM"
    const val PREF_SONG_SORT_BY_ALPHABET = "PREF_SONG_SORT_BY_ALPHABET"
    const val PREF_SONG_SORT_BY_ARTIST = "PREF_SONG_SORT_BY_ARTIST"
    const val PREF_SONG_SORT_BY_DURATION = "PREF_SONG_SORT_BY_DURATION"
    const val PREF_SONG_SORT_BY_GENRE = "PREF_SONG_SORT_BY_GENRE"
    const val PREF_SONG_SORT_BY_RELEASE_YEAR = "PREF_SONG_SORT_BY_RELEASE_YEAR"
    const val PREF_SONG_SORT_BY_DATE_MODIFIED = "PREF_SONG_SORT_BY_DATE_MODIFIED"

    const val PREF_ARTIST_ORDER_BY = "PREF_ARTIST_ORDER_BY"
    const val PREF_ARTIST_SORT = "PREF_ARTIST_SORT"
    const val PREF_ARTIST_SORT_BY_ALPHABET = "PREF_ARTIST_SORT_BY_ALPHABET"
    const val PREF_ARTIST_SORT_BY_NUMBER_OF_SONGS = "PREF_ARTIST_SORT_BY_NUMBER_OF_SONGS"
    const val PREF_ARTIST_SORT_BY_NUMBER_OF_ALBUMS = "PREF_ARTIST_SORT_BY_NUMBER_OF_ALBUMS"

    const val PREF_GENRE_ORDER_BY = "PREF_GENRE_ORDER_BY"
    const val PREF_GENRE_SORT = "PREF_GENRE_SORT"
    const val PREF_GENRE_SORT_BY_ALPHABET = "PREF_GENRE_SORT_BY_ALPHABET"
    const val PREF_GENRE_SORT_BY_NUMBER_OF_SONGS = "PREF_GENRE_SORT_BY_NUMBER_OF_SONGS"

    const val PREF_FOLDER_ORDER_BY = "PREF_FOLDER_ORDER_BY"
    const val PREF_FOLDER_SORT = "PREF_FOLDER_SORT"
    const val PREF_FOLDER_SORT_BY_ALPHABET = "PREF_FOLDER_SORT_BY_ALPHABET"
    const val PREF_FOLDER_SORT_BY_NUMBER_OF_SONGS = "PREF_FOLDER_SORT_BY_NUMBER_OF_SONGS"

    const val PREF_PLAYLIST_ORDER_BY = "PREF_PLAYLIST_ORDER_BY"
    const val PREF_PLAYLIST_SORT = "PREF_PLAYLIST_SORT"
    const val PREF_PLAYLIST_SORT_BY_ALPHABET = "PREF_PLAYLIST_SORT_BY_ALPHABET"
    const val PREF_PLAYLIST_SORT_BY_CREATED_TIME = "PREF_PLAYLIST_SORT_BY_CREATED_TIME"
    const val PREF_PLAYLIST_SORT_BY_NUMBER_OF_SONGS = "PREF_PLAYLIST_SORT_BY_NUMBER_OF_SONGS"

    const val PREF_ORDER_BY_ASCENDING = "PREF_ORDER_BY_ASCENDING"
    const val PREF_ORDER_BY_DESCENDING = "PREF_ORDER_BY_DESCENDING"
}
